version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy-chain
    container_name: proxychain-container
    volumes:
      - ./tools/proxy-chain:/tools/proxy-chain
    ports:
      - "19050:9050"  # Tor
      - "18118:8118"  # Privoxy
      - "13128:3128"  # Squid
    network_mode: "bridge"
    restart: unless-stopped
    command: ["/usr/local/bin/start-proxy-chain.sh"]
